### ISSUE TITLE
Update UI tests to look for progress dialogs on login, create account, and logout

### ISSUE THREAD

**Issue by ColinKohler** [justbeneu/JustBe-Android#67]

**Comment by golf1052** [comment]
Tried testing the progress dialog for login and Espresso didn't find the progress dialog initially. (Old login tests still work).
Test (for displayed progress dialog) started working after I broke login so that it wouldn't go past the progress dialog.
I guess since the progress dialog doesn't require interaction Espresso doesn't detect it?
